using Newtonsoft.Json;

namespace Application.NewWorld.PerkBucketData
{
    internal class PerkImportDto
    {
        public string PerkBucketID { get; set; }
        public string PerkType { get; set; }
        public double? PerkChance { get; set; }
        public string IgnoreExclusiveLabelWeights { get; set; }
        public string Perk1 { get; set; }
        public string Perk2 { get; set; }
        public string Perk3 { get; set; }
        public string Perk4 { get; set; }
        public string Perk5 { get; set; }
        public string Perk6 { get; set; }
        public string Perk7 { get; set; }
        public string Perk8 { get; set; }
        public string Perk9 { get; set; }
        public string Perk10 { get; set; }
        public string Perk11 { get; set; }
        public string Perk12 { get; set; }
        public string Perk13 { get; set; }
        public string Perk14 { get; set; }
        public string Perk15 { get; set; }
        public string Perk16 { get; set; }
        public string Perk17 { get; set; }
        public string Perk18 { get; set; }
        public string Perk19 { get; set; }
        public string Perk20 { get; set; }
        public string Perk21 { get; set; }
        public string Perk22 { get; set; }
        public string Perk23 { get; set; }
        public string Perk24 { get; set; }
        public string Perk25 { get; set; }
        public string Perk26 { get; set; }
        public string Perk27 { get; set; }
        public string Perk28 { get; set; }
        public string Perk29 { get; set; }
        public string Perk30 { get; set; }
        public string Perk31 { get; set; }
        public string Perk32 { get; set; }
        public string Perk33 { get; set; }
        public string Perk34 { get; set; }
        public string Perk35 { get; set; }
        public string Perk36 { get; set; }
        public string Perk37 { get; set; }
        public string Perk38 { get; set; }
        public string Perk39 { get; set; }
        public string Perk40 { get; set; }
        public string Perk41 { get; set; }
        public string Perk42 { get; set; }
        public string Perk43 { get; set; }
        public string Perk44 { get; set; }
        public string Perk45 { get; set; }
        public string Perk46 { get; set; }
        public string Perk47 { get; set; }
        public string Perk48 { get; set; }
        public string Perk49 { get; set; }
        public string Perk50 { get; set; }
        public string Perk51 { get; set; }
        public string Perk52 { get; set; }
        public string Perk53 { get; set; }
        public string Perk54 { get; set; }
        public string Perk55 { get; set; }
        public string Perk56 { get; set; }
        public string Perk57 { get; set; }
        public string Perk58 { get; set; }
        public string Perk59 { get; set; }
        public string Perk60 { get; set; }
        public string Perk61 { get; set; }
        public string Perk62 { get; set; }
        public string Perk63 { get; set; }
        public string Perk64 { get; set; }
        public string Perk65 { get; set; }
        public string Perk66 { get; set; }
        public string Perk67 { get; set; }
        public string Perk68 { get; set; }
        public string Perk69 { get; set; }
        public string Perk70 { get; set; }
        public string Perk71 { get; set; }
        public string Perk72 { get; set; }
        public string Perk73 { get; set; }
        public string Perk74 { get; set; }
        public string Perk75 { get; set; }
        public string Perk76 { get; set; }
        public string Perk77 { get; set; }
        public string Perk78 { get; set; }
        public string Perk79 { get; set; }
        public string Perk80 { get; set; }
        public string Perk81 { get; set; }
        public string Perk82 { get; set; }
        public string Perk83 { get; set; }
        public string Perk84 { get; set; }
        public string Perk85 { get; set; }
        public string Perk86 { get; set; }
        public string Perk87 { get; set; }
        public string Perk88 { get; set; }
        public string Perk89 { get; set; }
        public string Perk90 { get; set; }
        public string Perk91 { get; set; }
        public string Perk92 { get; set; }
        public string Perk93 { get; set; }
        public string Perk94 { get; set; }
        public string Perk95 { get; set; }
        public string Perk96 { get; set; }
        public string Perk97 { get; set; }
        public string Perk98 { get; set; }
        public string Perk99 { get; set; }
        public string Perk100 { get; set; }
        public string Perk101 { get; set; }
        public string Perk102 { get; set; }
        public string Perk103 { get; set; }
        public string Perk104 { get; set; }
        public string Perk105 { get; set; }
        public string Perk106 { get; set; }
        public string Perk107 { get; set; }
        public string Perk108 { get; set; }
        public string Perk109 { get; set; }
        public string Perk110 { get; set; }
        public string Perk111 { get; set; }
        public string Perk112 { get; set; }
        public string Perk113 { get; set; }
        public string Perk114 { get; set; }
        public string Perk115 { get; set; }
        public string Perk116 { get; set; }
        public string Perk117 { get; set; }
        public string Perk118 { get; set; }
        public string Perk119 { get; set; }
        public string Perk120 { get; set; }
        public string Perk121 { get; set; }
        public string Perk122 { get; set; }
        public string Perk123 { get; set; }
        public string Perk124 { get; set; }
        public string Perk125 { get; set; }
        public string Perk126 { get; set; }
        public string Perk127 { get; set; }
        public string Perk128 { get; set; }
        public string Perk129 { get; set; }
        public string Perk130 { get; set; }
        public string Perk131 { get; set; }
        public string Perk132 { get; set; }
        public string Perk133 { get; set; }
        public string Perk134 { get; set; }
        public string Perk135 { get; set; }
        public string Perk136 { get; set; }
        public string Perk137 { get; set; }
        public string Perk138 { get; set; }
        public string Perk139 { get; set; }
        public string Perk140 { get; set; }
        public string Perk141 { get; set; }
        public string Perk142 { get; set; }
        public string Perk143 { get; set; }
        public string Perk144 { get; set; }
        public string Perk145 { get; set; }
        public string Perk146 { get; set; }
        public string Perk147 { get; set; }
        public string Perk148 { get; set; }
        public string Perk149 { get; set; }
        public string Perk150 { get; set; }
        public string Perk151 { get; set; }
        public string Perk152 { get; set; }
        public string Perk153 { get; set; }
        public string Perk154 { get; set; }
        public string Perk155 { get; set; }
        public string Perk156 { get; set; }
        public string Perk157 { get; set; }
        public string Perk158 { get; set; }
        public string Perk159 { get; set; }
        public string Perk160 { get; set; }
        public string Perk161 { get; set; }
        public string Perk162 { get; set; }
        public string Perk163 { get; set; }
        public string Perk164 { get; set; }
        public string Perk165 { get; set; }
        public string Perk166 { get; set; }
        public string Perk167 { get; set; }
        public string Perk168 { get; set; }
        public string Perk169 { get; set; }
        public string Perk170 { get; set; }
        public string Perk171 { get; set; }
        public string Perk172 { get; set; }
        public string Perk173 { get; set; }
        public string Perk174 { get; set; }
        public string Perk175 { get; set; }
        public string Perk176 { get; set; }
        public string Perk177 { get; set; }
        public string Perk178 { get; set; }
        public string Perk179 { get; set; }
        public string Perk180 { get; set; }
        public string Perk181 { get; set; }
        public string Perk182 { get; set; }
        public string Perk183 { get; set; }
        public string Perk184 { get; set; }
        public string Perk185 { get; set; }
        public string Perk186 { get; set; }
        public string Perk187 { get; set; }
        public string Perk188 { get; set; }
        public string Perk189 { get; set; }
        public string Perk190 { get; set; }
        public string Perk191 { get; set; }
        public string Perk192 { get; set; }
        public string Perk193 { get; set; }
        public string Perk194 { get; set; }
        public string Perk195 { get; set; }
        public string Perk196 { get; set; }
        public string Perk197 { get; set; }
        public string Perk198 { get; set; }
        public string Perk199 { get; set; }
        public string Perk200 { get; set; }
        public string Perk201 { get; set; }
        public string Perk202 { get; set; }
        public string Perk203 { get; set; }
        public string Perk204 { get; set; }
        public string Perk205 { get; set; }
        public string Perk206 { get; set; }
        public string Perk207 { get; set; }
        public string Perk208 { get; set; }
        public string Perk209 { get; set; }
        public string Perk210 { get; set; }
        public string Perk211 { get; set; }
        public string Perk212 { get; set; }
        public string Perk213 { get; set; }
        public string Perk214 { get; set; }
        public string Perk215 { get; set; }
        public string Perk216 { get; set; }
        public string Perk217 { get; set; }
        public string Perk218 { get; set; }
        public string Perk219 { get; set; }
        public string Perk220 { get; set; }
        public string Perk221 { get; set; }
        public string Perk222 { get; set; }
        public string Perk223 { get; set; }
        public string Perk224 { get; set; }
        public string Perk225 { get; set; }
        public string Perk226 { get; set; }
        public string Perk227 { get; set; }
        public string Perk228 { get; set; }
        public string Perk229 { get; set; }
        public string Perk230 { get; set; }
        public string Perk231 { get; set; }
        public string Perk232 { get; set; }
        public string Perk233 { get; set; }
        public string Perk234 { get; set; }
        public string Perk235 { get; set; }
        public string Perk236 { get; set; }
        public string Perk237 { get; set; }
        public string Perk238 { get; set; }
        public string Perk239 { get; set; }
        public string Perk240 { get; set; }
        public string Perk241 { get; set; }
        public string Perk242 { get; set; }
        public string Perk243 { get; set; }
        public string Perk244 { get; set; }
        public string Perk245 { get; set; }
        public string Perk246 { get; set; }
        public string Perk247 { get; set; }
        public string Perk248 { get; set; }
        public string Perk249 { get; set; }
        public string Perk250 { get; set; }
        public string Perk251 { get; set; }
        public string Perk252 { get; set; }
        public string Perk253 { get; set; }
        public string Perk254 { get; set; }
        public string Perk255 { get; set; }
        public string Perk256 { get; set; }
        public string Perk257 { get; set; }
        public string Perk258 { get; set; }
        public string Perk259 { get; set; }
        public string Perk260 { get; set; }
        public string Perk261 { get; set; }
        public string Perk262 { get; set; }
        public string Perk263 { get; set; }
        public string Perk264 { get; set; }
        public string Perk265 { get; set; }
        public string Perk266 { get; set; }
        public string Perk267 { get; set; }
        public string Perk268 { get; set; }
        public string Perk269 { get; set; }
        public string Perk270 { get; set; }
        public string Perk271 { get; set; }
        public string Perk272 { get; set; }
        public string Perk273 { get; set; }
        public string Perk274 { get; set; }
        public string Perk275 { get; set; }
        public string Perk276 { get; set; }
        public string Perk277 { get; set; }
        public string Perk278 { get; set; }
        public string Perk279 { get; set; }
        public string Perk280 { get; set; }
        public string Perk281 { get; set; }
        public string Perk282 { get; set; }
        public string Perk283 { get; set; }
        public string Perk284 { get; set; }
        public string Perk285 { get; set; }
        public string Perk286 { get; set; }
        public string Perk287 { get; set; }
        public string Perk288 { get; set; }
        public string Perk289 { get; set; }
        public string Perk290 { get; set; }
        public string Perk291 { get; set; }
        public string Perk292 { get; set; }
        public string Perk293 { get; set; }
        public string Perk294 { get; set; }
        public string Perk295 { get; set; }
        public string Perk296 { get; set; }
        public string Perk297 { get; set; }
        public string Perk298 { get; set; }
        public string Perk299 { get; set; }
        public string Perk300 { get; set; }
        public string Perk301 { get; set; }
        public string Perk302 { get; set; }
        public string Perk303 { get; set; }
        public string Perk304 { get; set; }
        public string Perk305 { get; set; }
        public string Perk306 { get; set; }
        public string Perk307 { get; set; }
        public string Perk308 { get; set; }
        public string Perk309 { get; set; }
        public string Perk310 { get; set; }
        public string Perk311 { get; set; }
        public string Perk312 { get; set; }
        public string Perk313 { get; set; }
        public string Perk314 { get; set; }
        public string Perk315 { get; set; }
        public string Perk316 { get; set; }
        public string Perk317 { get; set; }
        public string Perk318 { get; set; }
        public string Perk319 { get; set; }
        public string Perk320 { get; set; }
        public string Perk321 { get; set; }
        public string Perk322 { get; set; }
        public string Perk323 { get; set; }
        public string Perk324 { get; set; }
        public string Perk325 { get; set; }
        public string Perk326 { get; set; }
        public string Perk327 { get; set; }
        public string Perk328 { get; set; }
        public string Perk329 { get; set; }
        public string Perk330 { get; set; }
        public string Perk331 { get; set; }
        public string Perk332 { get; set; }
        public string Perk333 { get; set; }
        public string Perk334 { get; set; }
        public string Perk335 { get; set; }
        public string Perk336 { get; set; }
        public string Perk337 { get; set; }
        public string Perk338 { get; set; }
        public string Perk339 { get; set; }
        public string Perk340 { get; set; }
        public string Perk341 { get; set; }
        public string Perk342 { get; set; }
        public string Perk343 { get; set; }
        public string Perk344 { get; set; }
        public string Perk345 { get; set; }
        public string Perk346 { get; set; }
        public string Perk347 { get; set; }
        public string Perk348 { get; set; }
        public string Perk349 { get; set; }
        public string Perk350 { get; set; }
        public string Perk351 { get; set; }
        public string Perk352 { get; set; }
        public string Perk353 { get; set; }
        public string Perk354 { get; set; }
        public string Perk355 { get; set; }
        public string Perk356 { get; set; }
        public string Perk357 { get; set; }
        public string Perk358 { get; set; }
        public string Perk359 { get; set; }
        public string Perk360 { get; set; }
        public string Perk361 { get; set; }
        public string Perk362 { get; set; }
        public string Perk363 { get; set; }
        public string Perk364 { get; set; }
        public string Perk365 { get; set; }
        public string Perk366 { get; set; }
        public string Perk367 { get; set; }
        public string Perk368 { get; set; }
        public string Perk369 { get; set; }
        public string Perk370 { get; set; }
        public string Perk371 { get; set; }
        public string Perk372 { get; set; }
        public string Perk373 { get; set; }
        public string Perk374 { get; set; }
        public string Perk375 { get; set; }
        public string Perk376 { get; set; }
        public string Perk377 { get; set; }
        public string Perk378 { get; set; }
        public string Perk379 { get; set; }
        public string Perk380 { get; set; }
        public string Perk381 { get; set; }
        public string Perk382 { get; set; }
        public string Perk383 { get; set; }
        public string Perk384 { get; set; }
        public string Perk385 { get; set; }
        public string Perk386 { get; set; }
        public string Perk387 { get; set; }
        public string Perk388 { get; set; }
        public string Perk389 { get; set; }
        public string Perk390 { get; set; }
        public string Perk391 { get; set; }
        public string Perk392 { get; set; }
        public string Perk393 { get; set; }
        public string Perk394 { get; set; }
        public string Perk395 { get; set; }
        public string Perk396 { get; set; }
        public string Perk397 { get; set; }
        public string Perk398 { get; set; }
        public string Perk399 { get; set; }
        public string Perk400 { get; set; }
        public string Perk401 { get; set; }
        public string Perk402 { get; set; }
        public string Perk403 { get; set; }
        public string Perk404 { get; set; }
        public string Perk405 { get; set; }
        public string Perk406 { get; set; }
        public string Perk407 { get; set; }
        public string Perk408 { get; set; }
        public string Perk409 { get; set; }
        public string Perk410 { get; set; }
        public string Perk411 { get; set; }
        public string Perk412 { get; set; }
        public string Perk413 { get; set; }
        public string Perk414 { get; set; }
        public string Perk415 { get; set; }
        public string Perk416 { get; set; }
        public string Perk417 { get; set; }
        public string Perk418 { get; set; }
        public string Perk419 { get; set; }
        public string Perk420 { get; set; }
        public string Perk421 { get; set; }
        public string Perk422 { get; set; }
        public string Perk423 { get; set; }
        public string Perk424 { get; set; }
        public string Perk425 { get; set; }
        public string Perk426 { get; set; }
        public string Perk427 { get; set; }
        public string Perk428 { get; set; }
        public string Perk429 { get; set; }
        public string Perk430 { get; set; }
        public string Perk431 { get; set; }
        public string Perk432 { get; set; }
        public string Perk433 { get; set; }
        public string Perk434 { get; set; }
        public string Perk435 { get; set; }
        public string Perk436 { get; set; }
        public string Perk437 { get; set; }
        public string Perk438 { get; set; }
        public string Perk439 { get; set; }
        public string Perk440 { get; set; }
        public string Perk441 { get; set; }
        public string Perk442 { get; set; }
        public string Perk443 { get; set; }
        public string Perk444 { get; set; }
        public string Perk445 { get; set; }
        public string Perk446 { get; set; }
        public string Perk447 { get; set; }
        public string Perk448 { get; set; }
        public string Perk449 { get; set; }
        public string Perk450 { get; set; }
        public string Perk451 { get; set; }
        public string Perk452 { get; set; }
        public string Perk453 { get; set; }
        public string Perk454 { get; set; }
        public string Perk455 { get; set; }
        public string Perk456 { get; set; }
        public string Perk457 { get; set; }
        public string Perk458 { get; set; }
        public string Perk459 { get; set; }
        public string Perk460 { get; set; }
        public string Perk461 { get; set; }
        public string Perk462 { get; set; }
        public string Perk463 { get; set; }
        public string Perk464 { get; set; }
        public string Perk465 { get; set; }
        public string Perk466 { get; set; }
        public string Perk467 { get; set; }
        public string Perk468 { get; set; }
        public string Perk469 { get; set; }
        public string Perk470 { get; set; }
        public string Perk471 { get; set; }
        public string Perk472 { get; set; }
        public string Perk473 { get; set; }
        public string Perk474 { get; set; }
        public string Perk475 { get; set; }
        public string Perk476 { get; set; }
        public string Perk477 { get; set; }
        public string Perk478 { get; set; }
        public string Perk479 { get; set; }
        public string Perk480 { get; set; }
        public string Perk481 { get; set; }
        public string Perk482 { get; set; }
        public string Perk483 { get; set; }
        public string Perk484 { get; set; }
        public string Perk485 { get; set; }
        public string Perk486 { get; set; }
        public string Perk487 { get; set; }
        public string Perk488 { get; set; }
        public string Perk489 { get; set; }
        public string Perk490 { get; set; }
        public string Perk491 { get; set; }
        public string Perk492 { get; set; }
        public string Perk493 { get; set; }
        public string Perk494 { get; set; }
        public string Perk495 { get; set; }
        public string Perk496 { get; set; }
        public string Perk497 { get; set; }
        public string Perk498 { get; set; }
        public string Perk499 { get; set; }
        public string Perk500 { get; set; }

        [JsonProperty("CURRENT LIMIT")]
        public string CURRENTLIMIT { get; set; }
    }
}
